### PR TITLE
Add max_range heuristics for the Kinect

### PR DESCRIPTION
**Pull request by kbogert**
This patch implements a way to convert out-of-range readings from the kinect into usable maximum-range readings.  The current implementation cannot tell the difference between too close and too far readings, marking them both as NaN.  This causes problems with large spaces like hallways where we have readings to the left and right but nothing in the middle.  This is most apparent when running SLAM as you get wedges of unexplored region instead of it being marked empty.

**Gmapping without the heuristics in a long hallway:**
without_heuristics

**With heuristics turned on (robot was not moved)**
with_heuristics

This works by examining the readings to the left and right of a section of out of range readings.  If these are greater than half the max range we assume that the out of range readings are due to being too far away rather than too close.  A number of other heuristics are applied in an attempt to reduce false positives.  This patch is not perfect but it definitely takes are lot of the pain out of mapping large spaces.

Its most apparent failure I've noticed is when it gets too close to sharp edges, it might mistake the too-close readings depending on what it can see on the other side of the edge.  Still, the errors don't impact the map that much and this can be controlled by reducing the range_max setting both in this package and in gmapping.

### CODE REVIEW

**Comment by chadrockey** [comment]
This should probably be in a separate filter.

You should make a quick node that does this same logic, but on sensor_msgs/LaserScan instead of here.  This way, you can have both /scan and /scan_range_heuristic in the system.  You'll be able to compare both in RVIZ and truly understand any complications and issues.

I don't believe that there is anything dependent on the depth image in this new application.  However, if you can't find another package in turtlebot for that node, I can foster it here.

**Comment by chadrockey** [comment]
Actually, I believe this will also clear posts, dowel rods, and even legs that are placed in the deadzone while there is a wall behind.  If that wall is also > half the max range, then you'll end up with 2 sections of wall and you will clear the obstacle and the wall beyond.

**Comment by kbogert** [comment]
Hmm, the difficulty with putting this in a separate node is that we must make a distinction between invalid points (which should be NaN) and out of range points.  I'm doing that now by marking the out of range points -inf and then converting those to maxRange if they pass the heuristics, so at the very least this change would have to be made in this package to support it.  In other words, I need to know the difference between beams which are out of range readings and those which are invalid.

You are correct that obstacles which are too close will be cleared in this situation, but since their readings are currently set to NaN anyway, the mapping and localization packages don't ever see the obstacles anyway making this a small impact.  In gmapping for instance you'd have to move away from the legs in order to get a valid scan of them to add to your map regardless.

**Comment by chadrockey** [comment]
-Inf is reserved for objects that are too close to be measured accurately.  +Inf is for out of range points.

With the Kinect, you only get 0s whether the point is invalid or out of range.  Since there's no distinction, I mark each of these as NaNs in the output laserscan, so your approach should work on any section of NaNs in the output message.

As for the obstacles, this is, in fact, very important for costmaps and navigation.  There's a huge difference between not seeing an obstacle and seeing behind it.  When you see behind it, you actually clear it out of the costmap entirely, giving you the okay to drive through it.  The behavior before was that you marked the map, moved closer, you cannot see it, but the point is NaN so you leave the obstacle in the map where it was and are forced to drive around where you saw it (even if it's actually no longer there).

**Comment by kbogert** [comment]
With the kinect, there is a distinction!  As the kinect does triangulation, there will be numerous points in its field of view which are shadowed, with no depth information available.  These are rightly marked NaN in the laser output stream and cannot be converted to maxRange as they would be false readings.  The amount of shadowing is dependent on the distance to the object as well, with more NaN's being present in closer data.  The out of range readings though are different, representing the IR camera seeing no data at all for a given area.  These should be marked with some form of inf as you say, but at this point i'd be worried about breaking existing code if this was done.

I appreciate your point about clearing of obstacles but in my experience it just does not matter.  For the applications that would use a kinect (and thus these heuristics) for mapping the benefits of adding large empty space to the map outweigh the small risk of bumping into something.  Take automated exploration of a building for instance that attempts to explore unseen areas of the map while keeping a distance from known obstacles.  Hallways take forever in this case as the centers can only be marked empty when viewed from an angle with close enough wall behind it.  

I am not advocating turning this patch on for say, running amcl (though I have seen some small benefit in hallways).  But there is benefit in having it available when needed.

**Comment by chadrockey** [comment]
@piyushk can you confirm that the freenect driver outputs different values for shadowed vs no information returned?  Are these in the uint16_t representation or the float?

**Comment by kbogert** [comment]
The more I'm thinking about this the more I think your suggestion to put this in it's own node would be a good idea.  Then it can take in the current costmaps and disable itself when there are any obstacles in front of the robot's believed position.  Then it could be turned on in general without having to worry about obstacle clearing (since if the obstacle is too close and not on any map you'll hit it anyway).

Would you accept a pull that just sets all out of range values to -inf in the outgoing scan_msg if a configuration option were set?

**Comment by chadrockey** [comment]
You would want to use depthimage_to_laserscan for obstacle avoidance and use the kinect heuristics for mapping (probably not localization though).  That way you get the best of both worlds.

Also, -Inf is not appropriate for out of range values according to REP 117:
http://www.ros.org/reps/rep-0117.html

**Comment by kbogert** [comment]
Well I would say to use inf, but the problem is that you can't tell the difference between too close and too far, so error on the side of caution and use too close.

**Comment by piyushk** [comment]
The freenect driver returns information in the uint16_t format, and a value is returned for every pixel. The ROS wrapper simply pushes the data through (I'm using `memcpy` to copy the data provided by freenect into the message data structure). If there is some other special value apart from 0, then I'm not aware of it. However, it's been a long time since I've had to work on the freenect code, and may have forgotten.

@kbogert I've faced the exact same problem you've described, and I've already got @chadrockey's suggestion implemented here: https://github.com/utexas-bwi/segbot/blob/master/segbot_sensors/include/segbot_sensors/nan_to_inf_filter.h

**Comment by kbogert** [comment]
@piyushk Thank you for the code, but it suffers from all the same issues raised in this thread.  There will be many NaN's in the laser scan message depending on the parameters (depth_msg width, scan angle, scaling, etc.)  This would wrongly set them to maxRange.  This is why I would like to have the option of marking the valid entries in the outgoing scan_msg in this package with something other than NaN when the depth from the kinect is out of range, that way they can be dealt with by a later package that can apply heuristics in a sort of passing-the-buck way, I'm sorry if this was not clear.

**Comment by kbogert** [comment]
...... or not.  Either I'm going insane or the problem I was seeing when I wrote this code is completely gone.  I just looked at the scan data and there are a few NaN's in /scan but they are stable and I can filter them out, nothing like the randomness I was seeing last year.  Well I guess I can close this then and work on a better way of solving this problem.

**Pull request closed without merging**
